package code

func init() {
	register(ErrUserAlreadyExist, 400, "User already exists")
	register(ErrUserNotFound, 404, "User not found")
	register(ErrUserNotActive, 403, "User account is not active")
	register(ErrSuccess, 200, "OK")
	register(ErrUnknown, 500, "Server error: Unknown server error")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct")
	register(ErrValidation, 400, "Validation failed")
	register(ErrTokenInvalid, 401, "Token invalid")
	register(ErrDatabase, 500, "Server error: Database error")
	register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	register(ErrSignatureInvalid, 401, "Signature is invalid")
	register(ErrExpired, 401, "Token expired")
	register(ErrInvalidAuthHeader, 401, "Invalid authorization header")
	register(ErrMissingHeader, 401, "The `Authorization` header was empty")
	register(ErrPasswordIncorrect, 401, "Password was incorrect")
	register(ErrPermissionDenied, 403, "Permission denied")
	register(ErrEncodingFailed, 500, "Server error: Encoding failed due to an error with the data")
	register(ErrDecodingFailed, 500, "Server error: Decoding failed due to an error with the data")
	register(ErrInvalidJSON, 500, "Server error:Data is not valid JSON")
	register(ErrEncodingJSON, 500, "Server error: JSON data could not be encoded")
	register(ErrDecodingJSON, 500, "Server error: JSON data could not be decoded")
	register(ErrInvalidYaml, 500, "Server error:Data is not valid Yaml")
	register(ErrEncodingYaml, 500, "Server error: Yaml data could not be encoded")
	register(ErrDecodingYaml, 500, "Server error: Yaml data could not be decoded")
	register(ErrStoreNotInitialized, 500, "Server error: Store not initialized")
}
