// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/login": {
            "post": {
                "description": "Authenticate user with username and password, returns JWT token string",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user account is not active",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "List users with optional filters (username, email, role, status) and pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by username (partial match)",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by email (partial match)",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by role (user/admin)",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (active/inactive/deleted)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination (default: 20, max: 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Users listed successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.UserListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a user with username, nickname, avatar, email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - encryption error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{username}": {
            "get": {
                "description": "Get a user by username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing username",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a user by username (partial update supported). Non-admin can only update self and only username/nickname/avatar/email; admin can update username/nickname/avatar/email/password/status/role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by username. Non-admin can only logout (soft delete) self by setting status=deleted; admin can hard delete any user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing username",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{username}/password": {
            "post": {
                "description": "Change user password by username. User must provide old password for verification and can only change their own password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Change password request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ChangePwdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token, or incorrect old password",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error or encryption error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/wg/ip-pools": {
            "get": {
                "description": "List IP pools with optional filters and pagination. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "List IP pools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (active/disabled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination (default: 20, max: 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "IP pools listed successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.IPPoolListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new IP pool for WireGuard peer IP allocation. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Create IP pool",
                "parameters": [
                    {
                        "description": "IP pool information",
                        "name": "pool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateIPPoolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "IP pool created successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.IPPoolResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/wg/ip-pools/{id}/available-ips": {
            "get": {
                "description": "Get a list of available IP addresses from an IP pool. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Get available IPs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP Pool ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of IPs to return (default: 50, max: 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Available IPs retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.AvailableIPsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - IP pool not found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/wg/peers": {
            "get": {
                "description": "List WireGuard peers with optional filters and pagination. Admin can see all peers, regular users can only see their own peers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "List WireGuard peers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (active/disabled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by IP pool ID",
                        "name": "ip_pool_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by device name (partial match)",
                        "name": "device_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit for pagination (default: 20, max: 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Peers listed successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.WGPeerListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new WireGuard peer for a user. Admin can create peers for any user, regular users can only create peers for themselves.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Create WireGuard peer",
                "parameters": [
                    {
                        "description": "Peer information",
                        "name": "peer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateWGPeerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Peer created successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.WGPeerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/wg/peers/{id}": {
            "get": {
                "description": "Get a WireGuard peer by ID. Admin can get any peer, regular users can only get their own peers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Get WireGuard peer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Peer retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.WGPeerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid peer ID",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - peer not found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a WireGuard peer by ID. Admin can update any peer, regular users can only update their own peers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Update WireGuard peer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Peer update information",
                        "name": "peer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateWGPeerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Peer updated successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.WGPeerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - peer not found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a WireGuard peer by ID. Admin can delete any peer, regular users can only delete their own peers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Delete WireGuard peer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Peer deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid peer ID",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - peer not found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/wg/peers/{id}/config": {
            "get": {
                "description": "Download the WireGuard client configuration file for a peer. Admin can download any peer's config, regular users can only download their own peer configs.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Download WireGuard peer configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration file content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid peer ID",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - peer not found or config file not found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.ErrResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code defines the business error code.",
                    "type": "integer"
                },
                "details": {
                    "description": "Details contains detailed validation error information.\nThis field is only present when validation errors occur.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Message contains the detail of this message.\nThis message is suitable to be exposed to external",
                    "type": "string"
                },
                "reference": {
                    "description": "Reference returns the reference document which maybe useful to solve this error.",
                    "type": "string"
                }
            }
        },
        "core.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code defines the business success code.",
                    "type": "integer"
                },
                "message": {
                    "description": "Message contains the success message.",
                    "type": "string"
                }
            }
        },
        "v1.AvailableIPsResponse": {
            "type": "object",
            "properties": {
                "cidr": {
                    "type": "string"
                },
                "ip_pool_id": {
                    "type": "string"
                },
                "ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.ChangePwdRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "description": "NewPassword is the user's new password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "oldPassword": {
                    "description": "OldPassword is the user's old password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "v1.CreateIPPoolRequest": {
            "type": "object",
            "required": [
                "cidr",
                "name",
                "server_ip"
            ],
            "properties": {
                "cidr": {
                    "description": "CIDR is the CIDR range for the IP pool (e.g., \"100.100.100.0/24\")",
                    "type": "string"
                },
                "description": {
                    "description": "Description is a description of the IP pool",
                    "type": "string",
                    "maxLength": 255
                },
                "gateway": {
                    "description": "Gateway is the gateway address (optional)",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the IP pool",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "server_ip": {
                    "description": "ServerIP is the server IP address in CIDR format (e.g., \"100.100.100.1/32\")",
                    "type": "string"
                }
            }
        },
        "v1.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "Avatar is the user's avatar URL (must be a valid URL, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "email": {
                    "description": "Email is the user's email address (must be valid email format and use common email provider, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "nickname": {
                    "description": "Nickname is the user's display name (3-32 characters). If not provided, will use username.",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "password": {
                    "description": "Password is the user's password (8-32 characters, will be hashed and not returned in response)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "description": "Username is the unique username for the user (3-32 characters, URL-safe, no Chinese)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "v1.CreateWGPeerRequest": {
            "type": "object",
            "required": [
                "device_name"
            ],
            "properties": {
                "allowed_ips": {
                    "description": "AllowedIPs is the allowed IPs for the peer (comma-separated CIDRs, optional, uses server default if not provided)",
                    "type": "string"
                },
                "client_ip": {
                    "description": "ClientIP is the IP address to assign to the client (optional, will be auto-allocated if not provided)\nFormat: IPv4 address without CIDR (e.g., \"100.100.100.2\")",
                    "type": "string"
                },
                "client_private_key": {
                    "description": "ClientPrivateKey is the WireGuard private key (optional, will be auto-generated if not provided)",
                    "type": "string"
                },
                "device_name": {
                    "description": "DeviceName is the name of the device (e.g., \"My Laptop\", \"iPhone\")",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "dns": {
                    "description": "DNS is the DNS server(s) for the client (comma-separated, optional, uses server default if not provided)",
                    "type": "string"
                },
                "endpoint": {
                    "description": "Endpoint is the server endpoint (optional, uses server default if not provided)",
                    "type": "string"
                },
                "ip_pool_id": {
                    "description": "IPPoolID is the ID of the IP pool to allocate from (required if ClientIP is not provided)",
                    "type": "string"
                },
                "persistent_keepalive": {
                    "description": "PersistentKeepalive is the keepalive interval in seconds (optional, default 25)",
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 0
                },
                "user_id": {
                    "description": "UserID is the ID of the user who owns this peer (admin can specify, regular user uses their own ID)",
                    "type": "string"
                }
            }
        },
        "v1.IPPoolListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.IPPoolResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.IPPoolResponse": {
            "type": "object",
            "properties": {
                "cidr": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "server_ip": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password is the user's password",
                    "type": "string"
                },
                "username": {
                    "description": "Username is the user's username",
                    "type": "string"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the JWT token for authentication",
                    "type": "string"
                }
            }
        },
        "v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar is the user's avatar URL (must be a valid URL, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "email": {
                    "description": "Email is the user's email address (must use common email provider domain, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "nickname": {
                    "description": "Nickname is the user's display name (3-32 characters)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "password": {
                    "description": "Password is the user's password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "role": {
                    "description": "Role is the user role (user/admin)",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                },
                "status": {
                    "description": "Status is the user status (active/inactive/deleted)",
                    "type": "string",
                    "enum": [
                        "active",
                        "inactive",
                        "deleted"
                    ]
                },
                "username": {
                    "description": "Username is the unique username for the user (3-32 characters, URL-safe, no Chinese)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "v1.UpdateWGPeerRequest": {
            "type": "object",
            "properties": {
                "allowed_ips": {
                    "description": "AllowedIPs is the allowed IPs for the peer (comma-separated CIDRs)",
                    "type": "string"
                },
                "device_name": {
                    "description": "DeviceName is the name of the device",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "dns": {
                    "description": "DNS is the DNS server(s) for the client (comma-separated)",
                    "type": "string"
                },
                "endpoint": {
                    "description": "Endpoint is the server endpoint",
                    "type": "string"
                },
                "persistent_keepalive": {
                    "description": "PersistentKeepalive is the keepalive interval in seconds",
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 0
                },
                "status": {
                    "description": "Status is the peer status (active/disabled)",
                    "type": "string",
                    "enum": [
                        "active",
                        "disabled"
                    ]
                }
            }
        },
        "v1.UserListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.UserResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.WGPeerListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.WGPeerResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.WGPeerResponse": {
            "type": "object",
            "properties": {
                "allowed_ips": {
                    "type": "string"
                },
                "client_ip": {
                    "type": "string"
                },
                "client_public_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "dns": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip_pool_id": {
                    "type": "string"
                },
                "persistent_keepalive": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "description": "Populated when listing peers",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
