// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/login": {
            "post": {
                "description": "Authenticate user with username and password, returns JWT token string",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user account is not active",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "description": "Create a user with username, nickname, avatar, email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - encryption error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{username}": {
            "get": {
                "description": "Get a user by username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing username",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a user by username (partial update supported). Non-admin can only update self and only username/nickname/avatar/email; admin can update username/nickname/avatar/email/password/status/role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "schema": {
                            "$ref": "#/definitions/v1.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by username. Non-admin can only logout (soft delete) self by setting status=deleted; admin can hard delete any user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing username",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{username}/password": {
            "post": {
                "description": "Change user password by username. User must provide old password for verification and can only change their own password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Change password request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ChangePwdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed successfully",
                        "schema": {
                            "$ref": "#/definitions/core.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or validation failed",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or expired token, or incorrect old password",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - permission denied",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database error or encryption error",
                        "schema": {
                            "$ref": "#/definitions/core.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.ErrResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code defines the business error code.",
                    "type": "integer"
                },
                "details": {
                    "description": "Details contains detailed validation error information.\nThis field is only present when validation errors occur.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Message contains the detail of this message.\nThis message is suitable to be exposed to external",
                    "type": "string"
                },
                "reference": {
                    "description": "Reference returns the reference document which maybe useful to solve this error.",
                    "type": "string"
                }
            }
        },
        "core.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code defines the business success code.",
                    "type": "integer"
                },
                "message": {
                    "description": "Message contains the success message.",
                    "type": "string"
                }
            }
        },
        "v1.ChangePwdRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "NewPassword is the user's new password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "old_password": {
                    "description": "OldPassword is the user's old password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "v1.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "Avatar is the user's avatar URL (must be a valid URL, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "email": {
                    "description": "Email is the user's email address (must be valid email format and use common email provider, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "nickname": {
                    "description": "Nickname is the user's display name (3-32 characters). If not provided, will use username.",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "password": {
                    "description": "Password is the user's password (8-32 characters, will be hashed and not returned in response)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "description": "Username is the unique username for the user (3-32 characters, URL-safe, no Chinese)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password is the user's password",
                    "type": "string"
                },
                "username": {
                    "description": "Username is the user's username",
                    "type": "string"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the JWT token for authentication",
                    "type": "string"
                }
            }
        },
        "v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar is the user's avatar URL (must be a valid URL, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "email": {
                    "description": "Email is the user's email address (must use common email provider domain, max 255 characters)",
                    "type": "string",
                    "maxLength": 255
                },
                "nickname": {
                    "description": "Nickname is the user's display name (3-32 characters)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "password": {
                    "description": "Password is the user's password (8-32 characters, will be hashed)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "role": {
                    "description": "Role is the user role (user/admin)",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                },
                "status": {
                    "description": "Status is the user status (active/inactive/deleted)",
                    "type": "string",
                    "enum": [
                        "active",
                        "inactive",
                        "deleted"
                    ]
                },
                "username": {
                    "description": "Username is the unique username for the user (3-32 characters, URL-safe, no Chinese)",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "v1.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
